// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: terrain_service.proto

package terrainservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerrainService_SubmitJob_FullMethodName    = "/terrainservice.TerrainService/SubmitJob"
	TerrainService_GetJobStatus_FullMethodName = "/terrainservice.TerrainService/GetJobStatus"
	TerrainService_GetUserJobs_FullMethodName  = "/terrainservice.TerrainService/GetUserJobs"
	TerrainService_GetLimit_FullMethodName     = "/terrainservice.TerrainService/GetLimit"
	TerrainService_SetLimit_FullMethodName     = "/terrainservice.TerrainService/SetLimit"
)

// TerrainServiceClient is the client API for TerrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TerrainServiceClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	GetUserJobs(ctx context.Context, in *GetUserJobsRequest, opts ...grpc.CallOption) (*GetUserJobsResponse, error)
	GetLimit(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*GetLimitResponse, error)
	SetLimit(ctx context.Context, in *SetLimitRequest, opts ...grpc.CallOption) (*SetLimitResponse, error)
}

type terrainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerrainServiceClient(cc grpc.ClientConnInterface) TerrainServiceClient {
	return &terrainServiceClient{cc}
}

func (c *terrainServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, TerrainService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terrainServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, TerrainService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terrainServiceClient) GetUserJobs(ctx context.Context, in *GetUserJobsRequest, opts ...grpc.CallOption) (*GetUserJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserJobsResponse)
	err := c.cc.Invoke(ctx, TerrainService_GetUserJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terrainServiceClient) GetLimit(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*GetLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitResponse)
	err := c.cc.Invoke(ctx, TerrainService_GetLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terrainServiceClient) SetLimit(ctx context.Context, in *SetLimitRequest, opts ...grpc.CallOption) (*SetLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLimitResponse)
	err := c.cc.Invoke(ctx, TerrainService_SetLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerrainServiceServer is the server API for TerrainService service.
// All implementations must embed UnimplementedTerrainServiceServer
// for forward compatibility.
type TerrainServiceServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	GetUserJobs(context.Context, *GetUserJobsRequest) (*GetUserJobsResponse, error)
	GetLimit(context.Context, *GetLimitRequest) (*GetLimitResponse, error)
	SetLimit(context.Context, *SetLimitRequest) (*SetLimitResponse, error)
	mustEmbedUnimplementedTerrainServiceServer()
}

// UnimplementedTerrainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerrainServiceServer struct{}

func (UnimplementedTerrainServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedTerrainServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedTerrainServiceServer) GetUserJobs(context.Context, *GetUserJobsRequest) (*GetUserJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserJobs not implemented")
}
func (UnimplementedTerrainServiceServer) GetLimit(context.Context, *GetLimitRequest) (*GetLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLimit not implemented")
}
func (UnimplementedTerrainServiceServer) SetLimit(context.Context, *SetLimitRequest) (*SetLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLimit not implemented")
}
func (UnimplementedTerrainServiceServer) mustEmbedUnimplementedTerrainServiceServer() {}
func (UnimplementedTerrainServiceServer) testEmbeddedByValue()                        {}

// UnsafeTerrainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerrainServiceServer will
// result in compilation errors.
type UnsafeTerrainServiceServer interface {
	mustEmbedUnimplementedTerrainServiceServer()
}

func RegisterTerrainServiceServer(s grpc.ServiceRegistrar, srv TerrainServiceServer) {
	// If the following call pancis, it indicates UnimplementedTerrainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerrainService_ServiceDesc, srv)
}

func _TerrainService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerrainService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerrainService_GetUserJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).GetUserJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_GetUserJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).GetUserJobs(ctx, req.(*GetUserJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerrainService_GetLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).GetLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_GetLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).GetLimit(ctx, req.(*GetLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerrainService_SetLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerrainServiceServer).SetLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerrainService_SetLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerrainServiceServer).SetLimit(ctx, req.(*SetLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerrainService_ServiceDesc is the grpc.ServiceDesc for TerrainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerrainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terrainservice.TerrainService",
	HandlerType: (*TerrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _TerrainService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _TerrainService_GetJobStatus_Handler,
		},
		{
			MethodName: "GetUserJobs",
			Handler:    _TerrainService_GetUserJobs_Handler,
		},
		{
			MethodName: "GetLimit",
			Handler:    _TerrainService_GetLimit_Handler,
		},
		{
			MethodName: "SetLimit",
			Handler:    _TerrainService_SetLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "terrain_service.proto",
}
